name: build_ErfanGSIs

on:
  watch:
    types: [started]
    
env:
  ROM_URL: https://objects.githubusercontent.com/github-production-release-asset-2e65be/362393580/6c656375-7191-4e6b-bae1-daf57bb3bfa1?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20221105%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20221105T163926Z&X-Amz-Expires=300&X-Amz-Signature=1702ed9b07bf2adeeb3b3f4d91306d8d91f17d66c989995011c2b45fc2079488&X-Amz-SignedHeaders=host&actor_id=117448159&key_id=0&repo_id=362393580&response-content-disposition=attachment%3B%20filename%3DPixelExperience_arm64-ab-13.0-20221104-UNOFFICIAL.img.xz&response-content-type=application%2Foctet-stream
  ROM_NAME: Pixel
  BUILD_AB: true
  BUILD_AONLY: false
  ROM_AONLY:
  ROM_AB: FLYME

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clean Up
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk p7zip gzip
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/lkx-0686/ErfanGSIs.git
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate Aonly GSI
         if: env.BUILD_AONLY == 'true'
         run: sudo ./ErfanGSIs/url2GSI.sh -a $ROM_URL $ROM_NAME
       
       - name: 7z Aonly GSI
         if: env.BUILD_AONLY == 'true'
         run: 7za a -t7z -r $ROM_AONLY ErfanGSIs/output/*
       
       - name: Upload Aonly GSI to WeTransfer
         if: env.BUILD_AONLY == 'true'
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet $ROM_AONLY
           
       - name: Clear output
         if: env.BUILD_AB == 'true'
         run: sudo rm -rf ErfanGSIs/output/*
         
       - name: Download Stock Rom & Generate AB GSI
         if: env.BUILD_AB == 'true'
         run: sudo ./ErfanGSIs/url2GSI.sh -b $ROM_URL $ROM_NAME

       - name: 7z AB GSI
         if: env.BUILD_AB == 'true'
         run: 7za a -t7z -r $ROM_AB ErfanGSIs/output/*

       - name: Upload AB GSI to WeTransfer
         if: env.BUILD_AB == 'true'
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet $ROM_AB
         
            
